const nav=[
  {
    "icon":$r("app.media.index_icon"),
    "selectedIcon":$r("app.media.index_icon_selected"),
    "mytxt":"首页",
    "color":Color.Black,
    "selected_color":Color.White
  },
  {
    "icon":$r("app.media.give_icon"),
    "selectedIcon":$r("app.media.give_icon_selected"),
    "mytxt":"捐助",
    "color":Color.Black,
    "selected_color":Color.White
  },
  {
    "icon":$r("app.media.love_icon"),
    "selectedIcon":$r("app.media.love_icon_selected"),
    "mytxt":"捐助岛",
    "color":Color.Black,
    "selected_color":Color.White
  },
  {
    "icon":$r("app.media.mine_icon"),
    "selectedIcon":$r("app.media.mine_icon_selected"),
    "mytxt":"我的",
    "color":Color.Black,
    "selected_color":Color.White
  }
]
export default nav
